FROM python:3.10-slim

WORKDIR /app

ENV PIP_DEFAULT_TIMEOUT=1000
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_NO_CACHE_DIR=1
ENV PIP_INDEX_URL=https://pypi.org/simple
ENV PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cpu

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.backend.txt .
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir --timeout 1000 --retries 10 -r requirements.backend.txt

COPY backend/ .

ENV PYTHONUNBUFFERED=1
ENV DB_PATH=/app/data/minicloud.db
ENV MLFLOW_TRACKING_URI=/app/mlruns

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
