FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.backend.txt .
RUN pip install --no-cache-dir -r requirements.backend.txt

COPY backend/ .

ENV PYTHONUNBUFFERED=1
ENV DB_PATH=/app/data/minicloud.db
ENV MLFLOW_TRACKING_URI=/app/mlruns

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
